apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin-deployment
  labels:
    app: xxl-job-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
      - name: xxl-job-admin
        image: registry.cn-hangzhou.aliyuncs.com/modds/xxl-job-admin:dev
        ports:
        - name: http
          containerPort: 39000
        imagePullPolicy: Never
      imagePullSecrets:
      - name: aliyun
      livenessProbe:
        httpGet:
          path: /actuator/health
          port: http
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 10